name: composite action
inputs:
  input1:  
    description: 'sample input'
    required: true
  input2:  
    description: 'sample input'
    required: true
  input3: 
    description: 'sample input'
    required: true

runs:
  using: "composite"
  steps:
    - name: Step 1
      run: echo "${{ inputs.input1 }}" 
      shell: bash


    - name: Step 2
      run: echo "${{ inputs.input2 }}" 
      shell: bash


    - name: Step 3
      run: echo "${{ inputs.input3 }}"  
      shell: bash

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash
