name: composite action
inputs:
  input1:  
    description: 'sample input'
    required: true
  input2:  
    description: 'sample input'
    required: true
  input3: 
    description: 'sample input'
    required: true

runs:
  using: "composite"
  steps:
    - name: Step 1
      shell: bash
      run: echo "${{ inputs.input1 }}" 

    - name: Step 2
      shell: bash
      run: echo "${{ inputs.input2 }}" 

    - name: Step 3
      shell: bash
      run: echo "${{ inputs.input3 }}"  

    - name: Run goodbye.sh
      shell: bash
      run: goodbye.sh
